<# 
    .NOTES 
    -------------------------------------------------------------------------------- 
     Code generated by:  Yours truly, the "Oh Shit" Guy 
     Generated on:       04/09/20201   
     Generated by:       It peeps on a Friday afternoon 
    -------------------------------------------------------------------------------- 
    .DESCRIPTION 
        MARINE CORE HOOO-RAAH

#>

function Main { 
    <# 
        .SYNOPSIS 
            The Main function starts the project application. 
         
        .PARAMETER Commandline 
            $Commandline contains the complete argument string passed to the script packager executable. 
         
        .NOTES 
            Use this function to initialize your script and to call GUI forms. 
             
        .NOTES 
            To get the console output in the Packager (Forms Engine) use:  
            $ConsoleOutput (Type: System.Collections.ArrayList) 
    #> 
        Param ([String]$Commandline) 
             
        #-------------------------------------------------------------------------- 
        #TODO: Add initialization script here (Load modules and check requirements) 
         
         
        #-------------------------------------------------------------------------- 
         
        if((Call-MainForm_psf) -eq 'OK') 
        { 
             
        } 
         
        #$global:ExitCode = 0 #Set the exit code for the Packager 
    } 

 
 
 
 
 
 
 
#endregion Source: Startup.pss 
 
#region Source: MainForm.psf 
function Call-MainForm_psf 
{ 
 
    #---------------------------------------------- 
    #region Import the Assemblies 
    #---------------------------------------------- 
    [void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') 
    [void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') 
    [void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') 
    #endregion Import Assemblies 
 
    #---------------------------------------------- 
    #region Generated Form Objects 
    #---------------------------------------------- 
    [System.Windows.Forms.Application]::EnableVisualStyles() 
    $MainForm = New-Object 'System.Windows.Forms.Form' 
    $panel2 = New-Object 'System.Windows.Forms.Panel' 
    $ButtonCancel = New-Object 'System.Windows.Forms.Button' 
    $ButtonWhatDidYouSayToMe = New-Object 'System.Windows.Forms.Button' 
    $panel1 = New-Object 'System.Windows.Forms.Panel' 
    $labelWhatDidYouSayToMe = New-Object 'System.Windows.Forms.Label' 
    $labelInOrderToApply = New-Object 'System.Windows.Forms.Label' 
    $timerUpdate = New-Object 'System.Windows.Forms.Timer' 
    $InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState' 
    #endregion Generated Form Objects 
 
    #---------------------------------------------- 
    # User Generated Script 
    #---------------------------------------------- 
    


    $MainForm_Load={ 
        #TODO: Initialize Form Controls here 
        #$labelTime.Text = "{0:D2}" -f $TotalTime #$TotalTime 
        #Add TotalTime to current time 
        $script:StartTime = (Get-Date).AddSeconds($TotalTime) 
        #Start the timer 
        $timerUpdate.Start() 
    } 



        $ButtonWhatDidYouSayToMe_Click = {
            $MainForm.Close()
        }

        $ButtonCancel_Click = {

            $MainForm.Close()
        }

        $panel2_Paint=[System.Windows.Forms.PaintEventHandler]{


        }


        $Form_StateCorrection_Load=
        {
            $MainForm.WindowState = $InitialFormWindowState
        }

        $Form_StoreValues_Closing=
        {
            #Control values here
        }
        $Form_Cleanup_FormClosed=
        {

            try 
            {
                $ButtonCancel.remove_Click($ButtonCancel_Click)
                $ButtonWhatDidYouSayToMe.remove_Click($ButtonWhatDidYouSayToMe_Click)
                $panel2.remove_Paint($panel2_Paint)
                $labelWhatDidYouSayToMe.remove_Click($labelWhatDidYouSayToMe)
                $labelInOrderToApply.remove_Click($labelInOrderToApply)
                $MainForm.remove_Load($MainForm_Load)
                $timerUpdate.remove_Tick($timerUpdate_Tick)
                $MainForm.remove_Load($Form_StateCorrection_Load)
                $MainForm.remove_Closing($Form_StoreValues_Closing)
                $MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
            }
            catch [Exception]
        
             { }
        }
        #endregion Generated Events



        #region Generated Form Code

        $MainForm.SuspendLayout()
        $panel2.SuspendLayout()
        $panel1.SuspendLayout()
        #
        # MainForm
        #
        $MainForm.Controls.Add($panel2) 
        $MainForm.Controls.Add($panel1)
        $MainForm.Controls.Add($labelWhatDidYouSayToMe)
        $MainForm.Controls.Add($labelInOrderToApply)
        $MainForm.AutoScaleDimensions = '3.9, 11' 
        $MainForm.AutoScaleMode = 'Font' 
        $MainForm.BackColor = 'White' 
        $MainForm.ClientSize = '658, 479' 
        $MainForm.MaximizeBox = $False 
        $MainForm.MinimizeBox = $False 
        $MainForm.ControlBox = $False
        $MainForm.Name = 'MainForm' 
        $MainForm.ShowIcon = $False 
        $MainForm.ShowInTaskbar = $False 
        $MainForm.StartPosition = 'CenterScreen'
        $MainForm.Text = 'What did you say to me you little punk?'
        $MainForm.TopMost = $true
        $MainForm.add_Load($MainForm_Load)
        #
        # panel2
        #
        $panel2.Controls.Add($ButtonWhatDidYouSayToMe)
        $panel2.Controls.Add($ButtonCancel)
        $panel2.BackColor = 'ScrollBar' 
        $panel2.Location = '0, 397' 
        $panel2.Name = 'panel2' 
        $panel2.Size = '658, 90' 
        $panel2.TabIndex = 9 
        $panel2.add_Paint($panel2_Paint)
        #
        # ButtonCancel
        #
        $ButtonCancel.Font = 'Microsoft Sans Serif, 10pt, style=Bold' 
        $ButtonCancel.Location = '495, 10' 
        $ButtonCancel.Name = 'ButtonCancel' 
        $ButtonCancel.Size = '120, 62' 
        $ButtonCancel.TabIndex = 7 
        $ButtonCancel.Text = 'Close' 
        $ButtonCancel.UseVisualStyleBackColor = $True 
        $ButtonCancel.add_Click($buttonCancel_Click) 
        #
        # ButtonWhatDidYouSayToMe
        #
        $ButtonWhatDidYouSayToMe.Font = 'Microsoft Sans Serif, 10pt, style=Bold'
        #$ButtonWhatDidYouSayToMe.ForeColor = 'DarkRed'
        $ButtonWhatDidYouSayToMe.Location = '42, 10'
        $ButtonWhatDidYouSayToMe.Name = 'ButtonWhatDidYouSayToMe'
        $ButtonWhatDidYouSayToMe.Size = '120, 62'
        $ButtonWhatDidYouSayToMe.TabIndex = 7
        $ButtonWhatDidYouSayToMe.Text = 'Close'
        $ButtonWhatDidYouSayToMe.UseVisualStyleBackColor = $true
        $ButtonWhatDidYouSayToMe.Add_Click($ButtonWhatDidYouSayToMe_Click)
        #
        # panel1
        #
        $panel1.Controls.Add($labelWhatDidYouSayToMe)
        $panel1.BackColor = '0, 114, 198' 
        $panel1.Location = '0, 0' 
        $panel1.Name = 'panel1' 
        $panel1.Size = '658, 80' 
        $panel1.TabIndex = 8 
        #
        # LabelWhatDidYouSayToMe
        #
        $labelWhatDidYouSayToMe.Font = 'Microsoft Sans Serif, 14pt'
        $labelWhatDidYouSayToMe.ForeColor = 'White'
        $labelWhatDidYouSayToMe.Location = '150, 28'
        $labelWhatDidYouSayToMe.Name = 'labelWhatDidYouSayToMe'
        $labelWhatDidYouSayToMe.Size = '400, 32'
        $labelWhatDidYouSayToMe.TabIndex = 1
        $labelWhatDidYouSayToMe.Text = "What the fuck did you just fucking say about me, you little bitch?"
        $labelWhatDidYouSayToMe.add_Click($labelWhatDidYouSayToMe_Click)
        #
        # labelInOrderToApply
        #
        $labelInOrderToApply.Font = 'Microsoft Sans Serif, 12pt'
        $labelInOrderToApply.Location = '8, 97'
        $labelInOrderToApply.Name = 'labelInOrderToApply'
        $labelInOrderToApply.Size = '658, 240'
        $labelInOrderToApply.TabIndex - 4
        $labelInOrderToApply.Text = "I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Qaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little 'clever' comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo. "
         # 
         # timerUpdate 
         # 
         $timerUpdate.add_Tick($timerUpdate_Tick) 
         $panel1.ResumeLayout() 
         $panel2.ResumeLayout() 
         $MainForm.ResumeLayout() 
         #endregion Generated Form Code 
 
        #---------------------------------------------- 

            #Save the initial state of the form 
    $InitialFormWindowState = $MainForm.WindowState 
    #Init the OnLoad event to correct the initial state of the form 
    $MainForm.add_Load($Form_StateCorrection_Load) 
    #Clean up the control events 
    $MainForm.add_FormClosed($Form_Cleanup_FormClosed) 
    #Store the control values when form is closing 
    $MainForm.add_Closing($Form_StoreValues_Closing) 
    #Show the Form 
    return $MainForm.ShowDialog() 
 
} 
#endregion Source: MainForm.psf 
 
#Start the application 
Main ($CommandLine) 

    


 